version: '3'

services:
  postgres:
    build:
      context: ./core/src/main/resources/db/schema
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
#      POSTGRES_DB: waste-finder
  adminer:
    image: adminer
    restart: always
    ports:
      - 9999:8080